name: gcc-13-all
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: 
   - cron: '0 12 * * 0'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
env:
  IMAGE: "cross-gcc"
  PACKAGE: "gcc"
  GCC_VERS: "13"
  DEB_VER: "sid"
  ARCH: "x86_64-linux-gnu"
  PLATFORM: "linux/amd64"
  PACKAGES: >
    gcc-13
    gcc-13-aarch64-linux-gnu
    gcc-13-alpha-linux-gnu
    gcc-13-arc-linux-gnu
    gcc-13-arm-linux-gnueabi
    gcc-13-arm-linux-gnueabihf
    gcc-13-hppa-linux-gnu
    gcc-13-i686-linux-gnu
    gcc-13-m68k-linux-gnu
    gcc-13-mips-linux-gnu
    gcc-13-mips64-linux-gnuabi64
    gcc-13-mips64el-linux-gnuabi64
    gcc-13-mipsel-linux-gnu
    gcc-13-mipsisa32r6-linux-gnu
    gcc-13-mipsisa32r6el-linux-gnu
    gcc-13-mipsisa64r6-linux-gnuabi64
    gcc-13-mipsisa64r6el-linux-gnuabi64
    gcc-13-powerpc-linux-gnu
    gcc-13-riscv64-linux-gnu
    gcc-13-s390x-linux-gnu
    gcc-13-sh4-linux-gnu
    gcc-13-sparc64-linux-gnu
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE}:all -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE}:13-all --build-arg PACKAGES="${PACKAGES}" --build-arg ARCH="${ARCH}" --build-arg DEB_VER="${DEB_VER}" --platform="${PLATFORM}" --push .
